### ISSUE TITLE
Catalina, node-gyp error, can't run create-ignition-theme 

### ISSUE THREAD

**Issue by petethompson** [saltnpixels/ignition#16]
Hello,

I'm trying to *try* ignition, but I can't get it up and running. I've been trying to run create-ignition-theme via npx for a couple days. I keep running into an error that seems to be related to fsevents package being out of date, and not compatible with node-gyp. 

I've gone down a rabbit hole of re-installing xcode and xcode command tools several times (which as you probably know is pretty time consuming). I've tried other solutions found in about 12 different Stackoverflow discussions. I keep running into the same exact issue. If there's a workaround for this, I'll keep trying but otherwise I'm throwing in the proverbial towel... This is what happens when I try to run npx create-ignition-theme, which I have to cancel out of because it just keeps looping. any help would be greatly appreciated:

npx: installed 10 in 2.725s
Downloading Ignition Starter Theme into theme-name
Ignition Theme Downloaded from git.
Running npm install...
npm WARN package.json ignition@3.5.0 No repository field.
npm WARN peerDependencies The peer dependency node-sass@^4.0.0 included from sass-loader will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency fibers@>= 3.1.0 included from sass-loader will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

> fsevents@2.1.3 install /Users/pete/WebServer/leafnation-litespeed/sites/leafnation.com/html/front-end/themes/theme-name/node_modules/sass/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

gyp: binding.gyp not found (cwd: /Users/pete/WebServer/leafnation-litespeed/sites/leafnation.com/html/front-end/themes/theme-name/node_modules/sass/node_modules/chokidar/node_modules/fsevents) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/pete/WebServer/leafnation-litespeed/sites/leafnation.com/html/front-end/themes/theme-name/node_modules/sass/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok`

**Comment by saltnpixels** [comment]
I went and updated all the dependencies on the project. Maybe try again?
What version of npm are you using?
and what version of node?

**Comment by saltnpixels** [comment]
I also see an issue because webpack 5 came out but browsersync isnt supporting it just yet....
I have downgraded the webpack back to v4

**Comment by petethompson** [comment]
I tried again and got the same result. 
I'm using npm 6.14.8 and node v12.16.1

By the way, when I search this gyp issue, with mac os, I get a lot of results pointing to some sort of issue with Catalina 10.15.x. So, this might be a compatibility issue Catalina/xcode/command line tools and node-gyp
